version: "3"

services:
  twitter-handler:
    image: tweet-sub-bot
    command: python run.py twitter
    build:
      context: .
      dockerfile: Dockerfile
  discord-bot:
    image: tweet-sub-bot
    command: python run.py discord
  # pub:
  #   image: tweet-sub-bot
  #   command: python pub.py
  # sub:
  #   image: tweet-sub-bot
  #   command: python sub.py
  redis:
    image: "redis:alpine"
